### ISSUE TITLE
Deploy Website to smconf.org

### ISSUE THREAD

**Issue by ch3ck** [silicon-mountain/smconf.org#15]
Deploy site and complete Social media pages.

**Comment by ch3ck** [comment]
@tahteche Use the Google Cloud Platform there.

**Comment by tahteche** [comment]
site is now online @ http://smconf2016.appspot.com. Custom domain will soon be added. From then on it will be about pulling updates and pushing to app engine

**Comment by ch3ck** [comment]
Nice @tahteche I think you should just close this issue once you've added the custom domain. @akamaotto should be able to assist here with the CPanel details.

**Comment by tahteche** [comment]
Deployed the latest fixes from master branch and custom domain is configured and active but not functional worldwide. Will take less than 48 hrs for it to propagate.

**Comment by ch3ck** [comment]
Aight nice @tahteche :+1:

**Comment by ch3ck** [comment]
@tahteche Can you please push the recent fixes to the site and take down smconf2016.appspot.com?

**Comment by tahteche** [comment]
Can't take down smconf2016.appspot.com. All appengine projects must have that default domain
