### ISSUE TITLE
seo issues on google

### ISSUE THREAD

**Issue by bosz** [silicon-mountain/smconf.org#17]
Searching the site on google does not give good information about the conference. 

https://www.google.cm/#q=smconf.org

![screenshot from 2016-04-19 23 12 33](https://cloud.githubusercontent.com/assets/6331902/14657244/8e7c2184-0684-11e6-9aaa-cd80f8334433.png)

**Comment by ch3ck** [comment]
@akamaotto  Can you look into this? The site should appear on Google search results.

**Comment by ch3ck** [comment]
@akamaotto @tahteche This link should help here: https://support.google.com/sites/answer/100283?hl=en

**Comment by wadleo** [comment]
Hi @Ch3ck 
Would like to work on this though you have assigned it to @akamaotto, waiting for your reply and while waiting will send a PR adding a meta tag for the site description.

**Comment by ch3ck** [comment]
Alright, you can work on this now. @wadleo

**Comment by wadleo** [comment]
Ok I have added the meta tag, and according the procedure specified by google to improve google searches and creation of a sitemap, the meta tag has to be verified. That is they have to check if the website has been modified with the meta tag. So I am currently waiting for the changes to be uploaded to the hosted site so google can verify and allow me to create a sitemap for the website hence enhancing searches for the site.

**Comment by tahteche** [comment]
@wadleo The changes have been deployed.

**Comment by bosz** [comment]
No change on google. 

Still same display as initial.

**Comment by wadleo** [comment]
kk i will complete the verification process now, thanks

**Comment by ch3ck** [comment]
When you complete that. You close this issue @wadleo

**Comment by wadleo** [comment]
kk working on it

**Comment by tahteche** [comment]
Changes have been deployed.

**Comment by Izakey** [comment]
Please we really need to fix this asap. Our SEO is really really BAD !

**Comment by xSavitar** [comment]
I think the SEO is perfect now. If I run a search in Google about the conference, I have a hit (first link) that points to the site :+1:

**Comment by xSavitar** [comment]
Since search is working perfectly, I think it will be a good idea to close this task and mark it as resolved :+1:
