### ISSUE TITLE
How do I register for SMConf2016 ?

### ISSUE THREAD

**Issue by Izakey** [silicon-mountain/smconf.org#23]
Add the link to the so-so ticket event or Eventbrite as the case may be.

**Comment by ch3ck** [comment]
we will use soso tickets.

**Comment by ch3ck** [comment]
I don't know if we'll need to link to the typeform or we'll generate the tickets for people who register on typeform. Let me talk to @mukete and see

**Comment by ch3ck** [comment]
Here is it: http://smconf.sosoticket.com/
