### ISSUE TITLE
Typos on Schedule Section

### ISSUE THREAD

**Issue by Izakey** [silicon-mountain/smconf.org#30]
I am creating these issues because I am severely hampered by not having a machine now. Please can someone fix these typos ?
1. Badge Pick-up timeslot is 07:00 am - 09:00 am. It doesn't have to end at 07:30 am.
2. After Hours time slot is 06:00 pm - 10:30 pm. It doesn't have to be from 07:00 pm.

**Comment by ch3ck** [comment]
Nice @ch3nkula make a PR. We'll merge :+1:

**Comment by Izakey** [comment]
@Ch3ck @ch3nkula Just [fixed](https://github.com/silicon-mountain/smconf.org/commit/1fd92c3e3c46778c2d9e86dc69f28f68c6deeff3) this issue
