### ISSUE TITLE
Sponsorship prospectus link does not link to document

### ISSUE THREAD

**Issue by ch3ck** [silicon-mountain/smconf.org#31]
Some recently added changes to the  sponsorship section and it appears it does not link to the prospectus. Could someone fix this?

**Comment by akamaotto** [comment]
Fixed, the problem was being caused by some gut ignore rule wrt pdf so we
linked the to the Dropbox pdf directly and it works now.
Regards

On Friday, 13 May 2016, Nyah Check notifications@github.com wrote:

> Assigned #31 https://github.com/silicon-mountain/smconf.org/issues/31
> to @akamaotto https://github.com/akamaotto.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/silicon-mountain/smconf.org/issues/31#event-659597605

##

**Comment by ch3ck** [comment]
Great then.
