### ISSUE TITLE
Remove/Disable "submit a talk" button and update that section 

### ISSUE THREAD

**Issue by bosz** [silicon-mountain/smconf.org#33]
Since period of submission of talks is over, i think the button should be removed or disabled and the text be changed to something that says submission of talks is over and maybe a link to presenters, their topic and abstracts. 

Regards

**Comment by Izakey** [comment]
Thanks, I'll edit the form response immediately

**Comment by bosz** [comment]
ok

**Comment by tahteche** [comment]
Please when done, ping me so I redeploy to App Engine.

**Comment by ch3ck** [comment]
Issue Fixed. Let me close this.
