### ISSUE TITLE
Add SMConf 2016 Report to current website

### ISSUE THREAD

**Issue by awasum** [silicon-mountain/smconf.org#35]

**Comment by BillYuga** [comment]
where do we get the event report for 2016 from?

**Comment by awasum** [comment]
@BillYuga Pictures and report for 2016 are available.

**Comment by BillYuga** [comment]
Yeah! I received them from @Izakey

**Comment by Izakey** [comment]
https://github.com/silicon-mountain/smconf.org/pull/45 Solves This Issue #35
