### ISSUE TITLE
Create Drop Down for Past Events

### ISSUE THREAD

**Issue by awasum** [silicon-mountain/smconf.org#36]
Given that more than 1 event has taken place, we need a drop down on the main menu taking people to previous event pictures and videos (probably subdomain: previous-year.smconf.org)

**Comment by chidelmun** [comment]
Working on this. PR Available by end of today.

**Comment by Izakey** [comment]
For The 2016 Archive, There's No Need For A Drop Down. We'll maintain the code snippet @chidelmun committed on the 2017 branch moving forward, albeit deprecating 2013 and 2014 as there was no SMConf Event then.
