### ISSUE TITLE
Update Readme.

### ISSUE THREAD

**Issue by chidelmun** [silicon-mountain/smconf.org#43]
1) The Instructions in the README should be generic.  We are not building any  sass code nor gulp tasks  so should update to **Deploy Locally** not **Build and Deploy**.

2) In Some cases, Port 8000 may already be used by another process so using that for development is not the best approach. The best way is to specify a free port
   
  **python  -m SimpleHTTPServer `<any Free port number>`  // Eg python -m SimpleHTTPServer 8002**

Alternatively the PhP inbuilt server will be best since we are not using any Python bindings.

   **php -S localhost:`<any free port> ` // Eg php -S localhost:8002**

These will deploy the site on port 8002.

README should be updated accordingly so new contributors can get their environment setup easily.

**Comment by xSavitar** [comment]
Please, make a PR and it will be merged. Thanks.

**Comment by xSavitar** [comment]
Also, if you need access to the Github organization, ask Isaac he will add you and you can lead the dev team working on the website. Thanks.

**Comment by Izakey** [comment]
Done, Check Readme File

**Comment by chidelmun** [comment]
Not everyone uses python 3 so this will not work for them
For python 3.x Users
 **python3 -m http.server <any-free-port> // E.g. python3 -m http.server 8000**

For python 2.x Users 👍 
***python -m SimpleHTTPServer <any-free-port> // E.g. python3 -m SimpleHTTPServer 8000**

**Comment by Izakey** [comment]
You have commit priviledges, edit the file . That should close discussions on this topic already

**Comment by chidelmun** [comment]
Thanks @Izakey Can someone invite me to the Gitter channel? I don't know what other tasks need to be done.

**Comment by Izakey** [comment]
@chidelmun Please write the "How To Contribute" Document Which You Just Talked About. It's needed for this phase. We're still setting things up so developers can get in and contribute. After this, we'll go on to editing content and style.
