### ISSUE TITLE
Need to write a contributing Document.

### ISSUE THREAD

**Issue by chidelmun** [silicon-mountain/smconf.org#44]
We need to write clear instructions for submitting pull requests. Its not professional for people to submit PR directly to the master branch.

New contributors should create a new branch and fix an issue or implement a new feature the push to that branch upstream not master. That way we can accept subsequent fixes for the same issues without losing old ones and commits are easy to manage. 

All this can still go into the README.

**Comment by xSavitar** [comment]
Stop talking and write the clear instructions and make a PR.

**Comment by Izakey** [comment]
@chidelmun I've just invited you to contribute to this repository. Kindly check your email, accept the invite and write out a "How To Contribute" Document. Please note that one of the by-laws here is that developers respect each other.

**Comment by chidelmun** [comment]
Roger that @Izakey I don't disrespect anyone. I'm just giving suggestions and also @ch3nkula Professionally speaking you cannot fix an issue that has not yet been raised and confirmed. Thats why I create issues then when approved I or anyone can tackle them.

**Comment by Izakey** [comment]
Still awaiting the Contributions Document @chidelmun

**Comment by chidelmun** [comment]
Fixed. Edits are welcomed.
