### ISSUE TITLE
Update the website for SMConf 2017

### ISSUE THREAD

**Issue by wadleo** [silicon-mountain/smconf.org#50]
Wire frame of changes done by Valery. Started working on the changes on the wire frame.

**Comment by chidelmun** [comment]
@wadleo are you currently working on this issue that way it can be assigned.

**Comment by wadleo** [comment]
yeah I am

**Comment by harryngatchu** [comment]
@wadleo how far with this issue?

**Comment by wadleo** [comment]
Yes sir @harryngatchu, this task was completed years ago
